name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ 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 }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Thank you for submitting this PR please wait for maintainace to merge'
